### ISSUE TITLE
Unexpected token 'export'

### ISSUE THREAD

**Issue by tadeas22** [cometkim/gatsby-plugin-linaria#113] opened 2020-12-16 14:41 UTC
Everytime i try to use styled as mentioned here https://github.com/callstack/linaria/blob/master/docs/BASICS.md#styling-custom-components result in SyntaxError

```
An unexpected runtime error ocurred during dependencies evaluation: 
/..../node_modules/@babel/runtime/helpers/esm/objectWithoutPropertiesLoose.js:1
(function (exports) { export default function _objectWithoutPropertiesLoose(source, excluded) {
                      ^^^^^^

SyntaxError: Unexpected token 'export'
    at new Script (vm.js:88:7)
```

`package.json`
```
...
    "linaria": "^2.0.2",
    "gatsby-plugin-linaria": "^2.2.0",
...
```

This issue https://github.com/callstack/linaria/issues/575#issuecomment-619789794 seems to be similar but last comment says that the error should be fixed

**Comment by MiltonAkash** [comment] 2020-12-18 16:50
Im experiencing the same issue

**Comment by pilniczek** [comment] 2021-01-08 00:59
Yeah, same here...

**Comment by cometkim** [comment] 2021-01-08 15:16
@tadeas22 @MiltonAkash @pilniczek

I'm unable to reproduce this bug in a new project. Could you share your project or a minimal reproduction public for debugging?

**Comment by MiltonAkash** [comment] 2021-01-08 15:18
Use styled from linaria and extend another component. You ll get this error

**Comment by cometkim** [comment] 2021-01-08 15:22
Yes that's exactly what I just tried

![image](https://user-images.githubusercontent.com/9696352/104031877-abc99000-5210-11eb-962a-bd9799d9dd2c.png)

**Comment by MiltonAkash** [comment] 2021-01-08 15:24
Is _Header a styled linaria component?? I got the error in that type of
case. Now I have rewritten the code to avoid such scenarios.

**Comment by cometkim** [comment] 2021-01-08 15:29
I cannot get error even I made a new `Header2` component by extending `Header` or a dummy styled component in header.jsx

**Comment by MiltonAkash** [comment] 2021-01-08 15:31
Maybe is it resolved🤔🤔

**Comment by cometkim** [comment] 2021-01-08 15:32
If you are using TypeScript, do you have `gatsby-plugin-typescript` in your gatsby-config?

https://github.com/cometkim/gatsby-plugin-linaria#typescript

**Comment by MiltonAkash** [comment] 2021-01-08 15:33
Not using typescript

**Comment by tadeas22** [comment] 2021-01-09 08:51
Finally i found the weird bug and i do not know how to explain it. [Here](https://gitlab.com/tadeas22/gatsby-linaria-error) is reproduction repository with 3 commits where second commit shows the bug and newest show how to fix it.

**Comment by cometkim** [comment] 2022-08-13 18:19
I expect this has resolved by upstream. try gatsby-plugin-linaria@v4 and reopen the bug still exist

**Closed by cometkim** 2022-08-13 18:19 UTC
Labels: bug, upstream
